SRC/Web/Controllers/SecuredController.cs
using System;

namespace GBFinance.Web.Controllers
{
    public class SecuredController : BaseLoanController
    {
        
    }
}

SRC/Web/Controllers/TestController.cs
using System;
using System.Web.Mvc;
using GBFinance.Web.Models;
using HiLand.General;
using HiLand.General.BLL;
using HiLand.General.DAL;
using HiLand.General.Entity;
using HiLand.Utility.Cache;
using HiLand.Utility.Data;
using HiLand.Utility.DataBase;

namespace GBFinance.Web.Controllers
{
    public class TestController : Controller
    {
        //
        // GET: /Test/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ControlTest()
        {
            return View();
        }

        public ActionResult CookieTest()
        {
            LoanCookie cookie = new LoanCookie();
            cookie.Load();
            this.ViewData["CurrentStep"] = cookie.CurrentStep;
            return View();
        }

        [HttpPost]
        public ActionResult CookieTest(bool? onlyPlaceHolder)
        {
            LoanCookie cookie = new LoanCookie();

            cookie.CurrentStep = 1;
            cookie.Save();
            this.ViewData["CurrentStep"] = cookie.CurrentStep;
            return View();
        }

        public ActionResult DisplayControllerName()
        {
            return View();
        }

        public ActionResult BLLTest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BLLTest(bool isplaceholder= true) 
        {
            LoanBasicBLL lbBLL = LoanBasicBLL.Instance;
            Guid guid = new Guid("d4b383c6-1c71-477d-948c-d30f9142a839");
            LoanBasicEntity entity = lbBLL.Get(guid);

            string loanString = string.Format("UPDATE [GeneralLoanBasic]   SET       [LoanStatus] =  [LoanStatus]+1  WHERE [LoanGuid] = '{0}'", "42d21e17-3140-482f-b0e6-56a4577e053a");
            LoanBasicDAL.HelperExInstance.ExecuteNonQuery(loanString);

            int i = 9;
            return View();
        }

        public ActionResult ClearCache()
        {
            CacheFactory.Create().Clear();
            return View();
        }

        public ActionResult DataBaseTest()
        {
            this.ViewData["result"] = SqlHelperEx.Instance.ConnectionString;
            return View();
        }

        [HttpPost]
        public ActionResult DataBaseTest(bool? onlyPlaceHolder)
        {
            this.ViewData["result"] = SqlHelperEx.Instance.ExecuteScalar("SELECT count(1)  FROM [CoreUser]").ToString();
            return View();
        }


        public ActionResult ValidateTest()
        {
            this.ViewData["Status"] = "Get";
            return View();
        }

        [HttpPost]
        public ActionResult ValidateTest(string myInput)
        {
            return Json(myInput);
        }

        public ActionResult ValidateTestResult(string myInput)
        {
            this.ViewData["Status"] = "Post";
            this.ViewData["MyInput"] = myInput;
            return View();
        }

        public ActionResult ValidateTestWrapper()
        {
            return View();
        }

        public ActionResult LoanScheduleTest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoanScheduleTest(bool? isOnlyPlaceHolder)
        { 
            //http://goldenbridgefinance.com.au/Manage/Secured/ScheduleList?loanGuid=017f7f83-5668-4f6b-99d9-913ce159878b#
            LoanBasicEntity loanBasicInfo =  LoanBasicBLL.Instance.Get("017f7f83-5668-4f6b-99d9-913ce159878b");
            LoanBasicBLL.Instance.GeneralSchedules(loanBasicInfo, DateTimeHelper.RunningLocalNow);
            return View();
        }

        public ActionResult TimeZoneTest()
        {
            return View();
        }
    }
}

SRC/Web/Views/Test/ClearCache.cshtml
@{
    ViewBag.Title = "ClearCache";
    Layout = null;
}

<h2>ClearCache</h2>

SRC/Web/Views/Test/ControlTest.cshtml
@using HiLand.Utility4.MVC.Controls

@{
    ViewBag.Title = "ControlTest";
}

<h2>ControlTest</h2>

<table>
    <tr>
        <td>@Html.HiTextBox().Lable("sss").Render()</td>
        <td>@Html.HiTextBox().Lable("bbb").Render()</td>
    </tr>
    @Html.HiTextBox().Lable("sssssssssssss").Render(new { aa="ssss",bb="ccccccccccc"})
</table>

@{Html.RenderAction("UAboutYourBusiness", "Secured");}

SRC/Web/Views/Test/CookieTest.cshtml
@{
    ViewBag.Title = "CookieTest";
    int currentStep = 0;
    if( this.ViewData["CurrentStep"]!=null)
    {
        currentStep = (int)this.ViewData["CurrentStep"];
    }

    string browserName= Request.Browser.Browser;
    bool isSupportCookie= Request.Browser.Cookies;
}

<h2>CookieTest</h2>

@using (Html.BeginForm())
{ 
    @currentStep.ToString()
    <input type="submit" value="Submit" />
}

============================<br />
@browserName <br />
@isSupportCookie

SRC/Web/Views/Test/DataBaseTest.cshtml
@{
    ViewBag.Title = "DataBaseTest";
    Layout = null;

    string result = (string)this.ViewData["result"];
}

<h2>DataBaseTest</h2>

@using (Html.BeginForm())
{ 
    <span>
        @result
    </span>
    <input type="submit" value="submit" />
}

SRC/Web/Views/Test/DisplayControllerName.cshtml
@{
    ViewBag.Title = "DisplayControllerName";
    string controllerName = HiLand.Utility4.MVC.MVCHelper.GetCurrentControllerName();
}

<h2>DisplayControllerName</h2>
@controllerName

SRC/Web/Views/Test/LoanScheduleTest.cshtml
@{
    ViewBag.Title = "LoanScheduleTest";
}

<h2>LoanScheduleTest</h2>
@using (Html.BeginForm())
{ 
    <input type="submit" value="Submit" />
}

SRC/Web/Views/Test/TimeZoneTest.cshtml
@{
    ViewBag.Title = "TimeZoneTest";
}

<h2>TimeZoneTest</h2>
服务器当前时间 ： @DateTime.Now <br />
修正时间： @HiLand.Utility.Data.DateTimeHelper.RunningLocalNow


===================
@HiLand.Utility.Setting.Config.GetAppSetting("TimeZoneDiff")

SRC/Web/Views/Test/ValidateTest.cshtml
@{
    ViewBag.Title = "ValidateTest";
    Layout = null;
}
@*    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.form.2.84.js")" type="text/javascript"></script>*@
<h2>
    ValidateTest</h2>
<div id="myDiv">
    @using (Html.BeginForm())
    { 
        <input type="text" name="myInput" id="myInput" />
        <br />
        <input type="button" name="mySubmit" id="mySubmit" value="submit" />
        <input type="button" name="myFormat" id="myFormat" value="format" />
        <input type="button" name="myConvert" id="myConvert" value="Convert" />
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#myDiv form").validate({
            rules: {
                myInput: "required"
            },
            messages: {
                myInput: "*"
            }
        });

        $("#mySubmit").click(function () {
            $("#myDiv form").ajaxSubmit({
                beforeSend: function () {
                    var result = $("#myDiv form").valid();
                    return result;
                },
                success: function (content) {
                    alert(content);
                }
            });
        });

        $("#myFormat").click(function () {
            var myString = jQuery.validator.format("welcome {0} to {1}", "Sun", "Qingdao");
            alert(myString);
        });

        $("#myConvert").click(function () {
            var myString ="5";
            alert(myString + 1);
            alert(+myString +1)
        });
        
    });
</script>

SRC/Web/Views/Test/ValidateTestResult.cshtml
@{
    ViewBag.Title = "ValidateTestResult";
    string status = this.ViewData["Status"].ToString();
    string myInput = string.Empty;

    if (this.ViewData["MyInput"] != null)
    {
        myInput = this.ViewData["MyInput"].ToString();
    }
}

<h2>ValidateTestResult</h2>
@status <br />
@myInput

<br />
@Html.ActionLink("Back","ValidateTest")

SRC/Web/Views/Test/ValidateTestWrapper.cshtml
@{
    
    ViewBag.Title = "ValidateTestWrapper";
}
<h2>
    ValidateTestWrapper</h2>
<div id="formContainer">
</div>
<input type="button" name="outerSubmit" id="outerSubmit" value="outerSubmit" />
<script type="text/javascript">
    $(document).ready(function () {
        $("#formContainer").load('@Url.Action("ValidateTest")');

        $("#formContainer form").validate({
            rules: {
                myInput: "required"
            },
            messages: {
                myInput: "*"
            }
        });


        $("#outerSubmit").click(function () {
            $("#formContainer form").ajaxSubmit({

                beforeSend: function () {
                    var result = $("#formContainer form").valid();
                    return result;
                },

                success: function (content) {
                    alert(content);
                }
            });
        });
    });
</script>

SRC/Web/Views/Test/blltest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <form method="post" >
            <input type="submit" />
        </form>
    </div>
</body>
</html>